//===----------------------------------------------------------------------===//
//
// This source file is part of the SwiftServiceLifecycle open source project
//
// Copyright (c) 2019-2020 Apple Inc. and the SwiftServiceLifecycle project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of SwiftServiceLifecycle project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//
//
// ComponentLifecycleTests+XCTest.swift
//
import XCTest

///
/// NOTE: This file was generated by generate_linux_tests.rb
///
/// Do NOT edit this file directly as it will be regenerated automatically when needed.
///

extension ComponentLifecycleTests {
    static var allTests: [(String, (ComponentLifecycleTests) -> () throws -> Void)] {
        return [
            ("testStartThenShutdown", testStartThenShutdown),
            ("testDeregister", testDeregister),
            ("testDeregisterAfterStart", testDeregisterAfterStart),
            ("testDefaultCallbackQueue", testDefaultCallbackQueue),
            ("testUserDefinedCallbackQueue", testUserDefinedCallbackQueue),
            ("testShutdownWhileStarting", testShutdownWhileStarting),
            ("testShutdownWhenIdle", testShutdownWhenIdle),
            ("testShutdownWhenIdleAndNoItems", testShutdownWhenIdleAndNoItems),
            ("testIfNotStartedWhenIdle", testIfNotStartedWhenIdle),
            ("testShutdownWhenShutdown", testShutdownWhenShutdown),
            ("testShutdownDuringHangingStart", testShutdownDuringHangingStart),
            ("testShutdownErrors", testShutdownErrors),
            ("testStartupErrors", testStartupErrors),
            ("testStartAndWait", testStartAndWait),
            ("testBadStartAndWait", testBadStartAndWait),
            ("testShutdownInOrder", testShutdownInOrder),
            ("testSync", testSync),
            ("testAyncBarrier", testAyncBarrier),
            ("testConcurrency", testConcurrency),
            ("testZeroTask", testZeroTask),
            ("testRegisterSync", testRegisterSync),
            ("testRegisterShutdownSync", testRegisterShutdownSync),
            ("testRegisterAsync", testRegisterAsync),
            ("testRegisterShutdownAsync", testRegisterShutdownAsync),
            ("testRegisterAsyncClosure", testRegisterAsyncClosure),
            ("testRegisterShutdownAsyncClosure", testRegisterShutdownAsyncClosure),
            ("testRegisterNIO", testRegisterNIO),
            ("testRegisterShutdownNIO", testRegisterShutdownNIO),
            ("testRegisterNIOClosure", testRegisterNIOClosure),
            ("testRegisterShutdownNIOClosure", testRegisterShutdownNIOClosure),
            ("testNIOFailure", testNIOFailure),
            ("testInternalState", testInternalState),
            ("testExternalState", testExternalState),
            ("testNOOPHandlers", testNOOPHandlers),
            ("testShutdownOnlyStarted", testShutdownOnlyStarted),
            ("testShutdownWhenStartFailedIfAsked", testShutdownWhenStartFailedIfAsked),
            ("testShutdownWhenStartFailsAndAsked", testShutdownWhenStartFailsAndAsked),
            ("testStatefulSync", testStatefulSync),
            ("testStatefulSyncStartError", testStatefulSyncStartError),
            ("testStatefulSyncShutdownError", testStatefulSyncShutdownError),
            ("testStatefulAsync", testStatefulAsync),
            ("testStatefulAsyncStartError", testStatefulAsyncStartError),
            ("testStatefulAsyncShutdownError", testStatefulAsyncShutdownError),
            ("testStatefulNIO", testStatefulNIO),
            ("testStatefulNIOStartFailure", testStatefulNIOStartFailure),
            ("testStatefulNIOShutdownFailure", testStatefulNIOShutdownFailure),
            ("testAsyncAwait", testAsyncAwait),
            ("testAsyncAwaitStateful", testAsyncAwaitStateful),
            ("testAsyncAwaitErrorOnStart", testAsyncAwaitErrorOnStart),
            ("testAsyncAwaitErrorOnStartShutdownRequested", testAsyncAwaitErrorOnStartShutdownRequested),
            ("testAsyncAwaitErrorOnShutdown", testAsyncAwaitErrorOnShutdown),
            ("testMetrics", testMetrics),
        ]
    }
}
