version: "3"

services:

  runtime-setup:
    image: swift-service-lifecycle:16.04-5.1
    build:
      args:
        ubuntu_version: "xenial"
        swift_version: "5.1"

  test:
    image: swift-service-lifecycle:16.04-5.1
    environment:
      - SANITIZER_ARG=--sanitize=thread
      - SKIP_SIGNAL_TEST=true

  shell:
    image: swift-service-lifecycle:16.04-5.1
