version: "3"

services:

  runtime-setup:
    image: swift-service-lifecycle:22.04-main
    build:
      args:
        base_image: "swiftlang/swift:nightly-main-jammy"

  test:
    image: swift-service-lifecycle:22.04-main
    environment:
      - SKIP_SIGNAL_TEST=true
      - FORCE_TEST_DISCOVERY=--enable-test-discovery

  shell:
    image: swift-service-lifecycle:22.04-main
