version: "3"

services:

  runtime-setup:
    image: swift-service-lifecycle:20.04-5.8
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.8-focal"

  test:
    image: swift-service-lifecycle:20.04-5.8
    environment:
      - SKIP_SIGNAL_TEST=true
      - FORCE_TEST_DISCOVERY=--enable-test-discovery

  shell:
    image: swift-service-lifecycle:20.04-5.8
