version: "3"

services:

  runtime-setup:
    image: swift-service-lifecycle:20.04-5.4
    build:
      args:
        base_image: "swiftlang/swift:nightly-5.4-focal"

  test:
    image: swift-service-lifecycle:20.04-5.4
    environment:
      - SKIP_SIGNAL_TEST=true

  shell:
    image: swift-service-lifecycle:20.04-5.4
